/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.duan1.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BA KHANG
 */
public class baocaodoanhthu extends javax.swing.JFrame {

    private JTable table;
    private JTextField txtSearch;
    private JButton btnTim;
    private JComboBox<String>[] comboBoxes;

    
    /**
     * Creates new form baocaodoanhthu
     */
    public baocaodoanhthu() {


        setTitle("Báo cáo doanh thu");
        setSize(1000, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // ==== Toàn bộ Panel chính ====
        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
        mainPanel.setBackground(new Color(245, 250, 255)); // pastel xanh nhẹ

        // ==== Tiêu đề ====
        JLabel lblTitle = new JLabel("Báo cáo doanh thu", JLabel.CENTER);
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 26));
        lblTitle.setForeground(new Color(20, 60, 100));
        mainPanel.add(lblTitle, BorderLayout.NORTH);

        // ==== Panel Tìm kiếm ====
        JPanel searchPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        searchPanel.setOpaque(false);
        txtSearch = new JTextField(30);
        btnTim = new JButton("Tìm");
        btnTim.setPreferredSize(new Dimension(70, 28));
        JLabel icon = new JLabel("\uD83D\uDD0D"); // icon kính lúp unicode

        txtSearch.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        btnTim.setFont(new Font("Segoe UI", Font.PLAIN, 13));

        searchPanel.add(icon);
        searchPanel.add(txtSearch);
        searchPanel.add(btnTim);
        mainPanel.add(searchPanel, BorderLayout.BEFORE_FIRST_LINE);

        // ==== Panel trung tâm: combobox + bảng ====
        JPanel centerPanel = new JPanel(new BorderLayout(5, 5));
        centerPanel.setOpaque(false);

        // ==== Panel ComboBox lọc ====
        String[] colNames = {"Mã NV", "Mã SP", "Tên SP", "Số lượng", "Tổng tiền", "Ngày lập"};
        String[][] comboOptions = {
            {"Từ A-Z", "Từ Z-A"},
            {"Từ A-Z", "Từ Z-A"},
            {"Từ A-Z", "Từ Z-A"},
            {"Tăng dần", "Giảm dần"},
            {"Tăng dần", "Giảm dần"},
            {"Mới nhất trước", "Cũ nhất trước"}
        };

        JPanel comboPanel = new JPanel(new GridLayout(1, colNames.length, 5, 0));
        comboPanel.setOpaque(false);
        comboBoxes = new JComboBox[colNames.length];

        for (int i = 0; i < colNames.length; i++) {
            comboBoxes[i] = new JComboBox<>(comboOptions[i]);
            comboBoxes[i].setFont(new Font("Segoe UI", Font.PLAIN, 12));
            comboBoxes[i].setPreferredSize(new Dimension(100, 25));
            comboPanel.add(comboBoxes[i]);
        }

        centerPanel.add(comboPanel, BorderLayout.NORTH);

        // ==== Bảng dữ liệu ====
        DefaultTableModel model = new DefaultTableModel(colNames, 0);
        table = new JTable(model);
        table.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        table.setRowHeight(24);
        table.setShowGrid(true);
        table.setGridColor(Color.LIGHT_GRAY);
        JScrollPane scrollPane = new JScrollPane(table);
        centerPanel.add(scrollPane, BorderLayout.CENTER);

        mainPanel.add(centerPanel, BorderLayout.CENTER);

        // ==== Panel phân trang ====
        JPanel pagingPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10));
        pagingPanel.setOpaque(false);

        String[] pageBtns = {"<<", "<", ">", ">>"};
        for (String label : pageBtns) {
            JButton btn = new JButton(label);
            btn.setFont(new Font("Segoe UI", Font.PLAIN, 13));
            btn.setPreferredSize(new Dimension(50, 28));
            pagingPanel.add(btn);
        }

        mainPanel.add(pagingPanel, BorderLayout.SOUTH);
        add(mainPanel);
        setVisible(true);
    }

    
        
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baocaodoanhthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baocaodoanhthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baocaodoanhthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baocaodoanhthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baocaodoanhthu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
